import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync, renameSync } from 'node:fs';
import { join } from 'node:path';
import type { ChatDebugSettingsService } from '../chat-debug-settings/index.js';
import type { OpenAIMessage, OpenAITool, ChatUsage } from '../chat-handler/index.js';
import type { RuleApplicationResult } from '../content-rules/index.js';
import {
  extractTextContent,
  extractImageParts,
  extractReasoning,
  extractReasoningFields,
  type ReasoningDetail,
  type ReasoningFields,
} from '../../utils/index.js';
import type { Logger } from '../../logger/index.js';

/** Input data for logging a chat request-response pair. */
export interface LogRequestInput {
  /** Unique request identifier (UUID), generated by the caller. */
  requestId: string;
  /**
   * Session ID resolved by the session tracker before the
   * request was sent. Used for the session directory name so
   * debug logs are attributed to the same conversation as the
   * `X-Session-Id` request header.
   */
  sessionId: string;
  /** Translated chat messages sent in the request. */
  messages: OpenAIMessage[];
  /** Accumulated response text content. */
  responseContent: string;
  /** Tool calls from the model response. */
  responseToolCalls: Array<{
    id: string;
    name: string;
    arguments: string;
  }>;
  /** Reasoning content from the model response (pre-extracted display string). */
  responseReasoning?: string | null;
  /**
   * Full reasoning fields from the model response, used to
   * render the structured field summary (which provider
   * fields were present, plus each reasoning block's
   * identity: `type`, `index`, `format`, `signature`, `id`).
   * When absent, the response reasoning section only renders
   * {@link responseReasoning}.
   */
  responseReasoningFields?: ReasoningFields | null;
  /**
   * Indices of assistant messages whose reasoning was
   * backfilled from the persistent cache. Assistant messages
   * with reasoning that are *not* in this set received their
   * reasoning from VS Code thinking parts (the primary
   * source). Used to annotate each message's reasoning
   * block with its source.
   */
  reasoningSources?: ReadonlySet<number> | null;
  /** Display name of the model (e.g. "provider/model-id"). */
  modelName: string;
  /** Sampling parameters and other model options. */
  modelOptions: Record<string, unknown>;
  /** Tool definitions sent with the request. */
  tools: OpenAITool[] | undefined;
  /** Tool calling mode ('auto' or 'required'). */
  toolMode?: 'auto' | 'required';
  /** When the request started. */
  startTime: Date;
  /** When the request completed. */
  endTime: Date;
  /** Whether the request was cancelled by the user. */
  cancelled: boolean;
  /** Error message if the request failed. */
  error: string | undefined;
  /** Workspace folder URI for computing workspace ID. */
  workspaceFolderUri: string;
  /** Workspace folder paths (for multi-root workspaces). */
  workspaceFolders: string[];
  /** Token usage from the API response, or null if unavailable. */
  usage?: ChatUsage | null;
  /**
   * Per-rule results from content rules application.
   * `undefined` when no content rules are configured.
   */
  contentRules?: RuleApplicationResult[];
}

const SENSITIVE_KEYS = new Set([
  'apikey',
  'api_key',
  'authorization',
  'token',
  'secret',
  'password',
  'bearer',
]);

/**
 * Strips sensitive keys from model options.
 *
 * @param opts - The raw model options.
 * @returns A copy with sensitive keys removed.
 */
function sanitizeOptions(opts: Record<string, unknown>): Record<string, unknown> {
  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(opts)) {
    if (!SENSITIVE_KEYS.has(key.toLowerCase())) {
      result[key] = value;
    }
  }
  return result;
}

/**
 * Formats a message role as a human-readable label.
 *
 * @param msg - The message to label.
 * @returns Capitalized role label (e.g. "System", "Tool Result").
 */
function formatRoleLabel(msg: OpenAIMessage): string {
  if (msg.role === 'tool') return 'Tool Result';
  return msg.role.charAt(0).toUpperCase() + msg.role.slice(1);
}

/**
 * Renders a compact summary of the structured reasoning
 * fields present on a message or response.
 *
 * Lists which provider-dependent fields are populated
 * (`reasoning_content`, `reasoning`, `reasoning_details`)
 * and, for each reasoning detail block, its identity
 * fields (`type`, `index`, `format`, `signature`, `id`)
 * plus the text length. This surfaces the exact fields the
 * upstream provider needs to verify a signed `thinking`
 * block, which is essential for debugging
 * `Invalid signature in thinking block` errors.
 *
 * @param fields - The reasoning fields to summarise.
 * @returns A multi-line summary string, or `''` when no
 *   reasoning fields are present.
 */
function formatReasoningFieldsSummary(fields: ReasoningFields): string {
  const extracted = extractReasoningFields(fields);
  if (!extracted) return '';

  const lines: string[] = ['Fields:'];

  if (typeof extracted.reasoning_content === 'string') {
    lines.push(`  reasoning_content (${extracted.reasoning_content.length} chars)`);
  }
  if (typeof extracted.reasoning === 'string') {
    lines.push(`  reasoning (${extracted.reasoning.length} chars)`);
  }
  if (Array.isArray(extracted.reasoning_details)) {
    lines.push(`  reasoning_details (${extracted.reasoning_details.length} block(s)):`);
    extracted.reasoning_details.forEach((detail, i) => {
      lines.push(`    [${i}] ${formatReasoningDetail(detail)}`);
    });
  }

  return lines.join('\n');
}

/**
 * Renders a single reasoning detail block's identity fields
 * as a compact one-line summary.
 *
 * @param detail - The reasoning detail entry.
 * @returns A compact summary like
 *   `type=reasoning.text index=0 format=anthropic-claude-v1 signature=152c id=blk_01 text=120c`.
 */
function formatReasoningDetail(detail: ReasoningDetail): string {
  const parts: string[] = [`type=${detail.type ?? ''}`];
  if (detail.index !== undefined) {
    parts.push(`index=${detail.index}`);
  }
  if (detail.format) {
    parts.push(`format=${detail.format}`);
  }
  // The signature is the field most relevant to
  // "Invalid signature in thinking block" errors; show its
  // presence and length rather than the (large) value to
  // keep the debug log readable.
  if (typeof detail.signature === 'string' && detail.signature) {
    parts.push(`signature=${detail.signature.length}c`);
  } else if (detail.signature === null) {
    parts.push('signature=null');
  } else {
    parts.push('signature=—');
  }
  if (detail.id) {
    parts.push(`id=${detail.id}`);
  }
  const textLen =
    typeof detail.text === 'string'
      ? detail.text.length
      : typeof detail.summary === 'string'
        ? (detail.summary as string).length
        : typeof detail.data === 'string'
          ? (detail.data as string).length
          : 0;
  parts.push(`text=${textLen}c`);
  return parts.join(' ');
}

/**
 * Writes chat request-response pairs as structured Markdown
 * log files to disk.
 *
 * Checks the debug settings before logging. Uses the
 * pre-resolved session ID (from the two-phase session
 * tracker) for session attribution. Writes atomically via
 * temp file + rename. Logging errors are silently swallowed
 * (fire-and-forget).
 */
export class ChatDebugLogger {
  /**
   * Creates a new ChatDebugLogger.
   *
   * @param settingsService - Service for reading debug settings.
   * @param logsBasePath - Base directory for log files.
   * @param logger - Logger for runtime diagnostics.
   * @param onLogWrite - Optional callback invoked after a
   *   successful log write to refresh the tree view.
   */
  constructor(
    private readonly settingsService: ChatDebugSettingsService,
    private readonly logsBasePath: string,
    private readonly logger: Logger,
    private readonly onLogWrite?: () => void,
  ) {}

  /**
   * Sanitizes a model name for use as a filesystem
   * directory name component.
   *
   * Replaces filesystem-unsafe characters (`/`, `\`, `:`,
   * `<`, `>`, `"`, `|`, `?`, `*`) with hyphens, collapses
   * consecutive hyphens, and trims leading/trailing hyphens.
   *
   * @param modelName - The raw model name.
   * @returns A filesystem-safe model name.
   */
  static sanitizeModelName(modelName: string): string {
    return modelName
      .replace(/[/\\:<>"|?*]/g, '-')
      .replace(/-{2,}/g, '-')
      .replace(/^-+|-+$/g, '');
  }

  /**
   * Computes a workspace ID from a workspace folder URI.
   *
   * @param uri - The workspace folder URI string.
   * @returns A 16-character hex string (truncated SHA-256).
   */
  static computeWorkspaceId(uri: string): string {
    return createHash('sha256').update(uri).digest('hex').slice(0, 16);
  }

  /**
   * Formats a Date as a filesystem-safe timestamp string.
   *
   * @param date - The date to format.
   * @returns Timestamp in `YYYYMMDD-HHmmss-SSS` format.
   */
  static formatTimestamp(date: Date): string {
    const y = date.getUTCFullYear();
    const mo = String(date.getUTCMonth() + 1).padStart(2, '0');
    const d = String(date.getUTCDate()).padStart(2, '0');
    const h = String(date.getUTCHours()).padStart(2, '0');
    const mi = String(date.getUTCMinutes()).padStart(2, '0');
    const s = String(date.getUTCSeconds()).padStart(2, '0');
    const ms = String(date.getUTCMilliseconds()).padStart(3, '0');
    return `${y}${mo}${d}-${h}${mi}${s}-${ms}`;
  }

  /**
   * Formats a log entry as a structured Markdown string.
   *
   * @param input - The request-response data to format.
   * @param requestId - Unique request identifier (UUID).
   * @returns The formatted Markdown content.
   */
  static formatLogMarkdown(input: LogRequestInput, requestId: string): string {
    const duration = input.endTime.getTime() - input.startTime.getTime();
    const toolCount = input.tools?.length ?? 0;
    const messageCount = input.messages.length;
    const safeOptions = sanitizeOptions(input.modelOptions);

    const sections: string[] = [];

    // Title
    sections.push(`# ChatRequest - ${requestId}`);
    sections.push('');

    // Table of contents
    sections.push('- [Metadata](#metadata)');
    sections.push('- [Messages](#messages)');
    ChatDebugLogger.buildTableOfContents(input.messages, sections);
    sections.push('- [Response](#response)');
    sections.push('');

    // Metadata
    ChatDebugLogger.buildMetadataBlock(
      input,
      requestId,
      duration,
      toolCount,
      messageCount,
      safeOptions,
      sections,
    );

    // Messages
    ChatDebugLogger.buildMessagesBlock(input.messages, input.reasoningSources ?? null, sections);

    // Response
    ChatDebugLogger.buildResponseBlock(input, sections);

    return sections.join('\n');
  }

  /**
   * Appends the table of contents entries for each message.
   *
   * @param messages - The chat messages.
   * @param sections - The output sections array to append to.
   */
  private static buildTableOfContents(messages: OpenAIMessage[], sections: string[]): void {
    for (let i = 0; i < messages.length; i++) {
      const label = formatRoleLabel(messages[i]);
      const anchor = `message-${i + 1}-${label.toLowerCase().replace(/\s+/g, '-')}`;
      sections.push(`    - [Message ${i + 1} (${label})](#${anchor})`);
    }
  }

  /**
   * Appends the full Metadata section (header, inline meta lines,
   * and collapsible sub-sections for tools, content rules, usage).
   *
   * @param input - The request-response data.
   * @param requestId - Unique request identifier.
   * @param duration - Computed request duration in ms.
   * @param toolCount - Number of tool definitions.
   * @param messageCount - Number of chat messages.
   * @param safeOptions - Sanitized model options.
   * @param sections - The output sections array to append to.
   */
  private static buildMetadataBlock(
    input: LogRequestInput,
    requestId: string,
    duration: number,
    toolCount: number,
    messageCount: number,
    safeOptions: Record<string, unknown>,
    sections: string[],
  ): void {
    sections.push('## Metadata');
    sections.push('');
    sections.push('<pre><code>');

    const metaLines = [
      `requestId     : ${requestId}`,
      `model         : ${input.modelName}`,
      `startTime     : ${input.startTime.toISOString()}`,
      `endTime       : ${input.endTime.toISOString()}`,
      `duration      : ${duration}ms`,
      `cancelled     : ${input.cancelled}`,
    ];

    if (toolCount > 0) {
      metaLines.push(`toolMode      : ${input.toolMode ?? 'auto'}`);
    }
    metaLines.push(`toolCount     : ${toolCount}`);
    metaLines.push(`messageCount  : ${messageCount}`);
    metaLines.push(`workspaces    : ${input.workspaceFolders.join(', ') || '(none)'}`);
    metaLines.push(`modelOptions  : ${JSON.stringify(safeOptions)}`);

    sections.push(metaLines.join('\n'));

    ChatDebugLogger.buildToolsBlock(input.tools, toolCount, sections);
    ChatDebugLogger.buildContentRulesBlock(input.contentRules, sections);
    ChatDebugLogger.buildUsageBlock(input.usage, sections);

    sections.push('</code></pre>');
    sections.push('');
  }

  /**
   * Appends the tools collapsible details block.
   *
   * @param tools - Tool definitions, if any.
   * @param toolCount - Number of tools.
   * @param sections - The output sections array to append to.
   */
  private static buildToolsBlock(
    tools: OpenAITool[] | undefined,
    toolCount: number,
    sections: string[],
  ): void {
    if (!tools || tools.length === 0) return;

    const toolNames = tools.map((t) => t.function.name).join(', ');
    const toolJson = tools.map((t) => ({
      name: t.function.name,
      description: t.function.description ?? '',
      parameters: t.function.parameters ?? {},
    }));
    sections.push('<details>');
    sections.push(`<summary>tools (${toolCount}): ${toolNames}</summary>`);
    sections.push('');
    sections.push('```json');
    sections.push(JSON.stringify(toolJson, null, 2));
    sections.push('```');
    sections.push('');
    sections.push('</details>');
  }

  /**
   * Appends the content rules collapsible details block.
   *
   * @param contentRules - Per-rule application results, or undefined.
   * @param sections - The output sections array to append to.
   */
  private static buildContentRulesBlock(
    contentRules: RuleApplicationResult[] | undefined,
    sections: string[],
  ): void {
    if (contentRules === undefined) return;

    const ruleCount = contentRules.length;
    const matchedCount = contentRules.filter((r) => r.matched).length;
    const appliedCount = contentRules.filter((r) => r.applied).length;
    sections.push('<details>');
    sections.push(
      `<summary>contentRules (${ruleCount}): ${matchedCount} matched, ${appliedCount} applied</summary>`,
    );
    sections.push('');
    sections.push('```json');
    sections.push(JSON.stringify(contentRules, null, 2));
    sections.push('```');
    sections.push('');
    sections.push('</details>');
  }

  /**
   * Appends the token usage collapsible details block.
   *
   * @param usage - Token usage info, or null/undefined.
   * @param sections - The output sections array to append to.
   */
  private static buildUsageBlock(usage: ChatUsage | null | undefined, sections: string[]): void {
    if (!usage) return;

    const u = usage;
    const total = u.promptTokens + u.completionTokens;
    let summary = `usage: prompt ${u.promptTokens} | completion ${u.completionTokens} | total ${total}`;
    if (u.cachedTokens > 0) summary += ` | cached ${u.cachedTokens}`;
    if (u.reasoningTokens > 0) summary += ` | reasoning ${u.reasoningTokens}`;
    sections.push('<details>');
    sections.push(`<summary>${summary}</summary>`);
    sections.push('');
    sections.push('```json');
    sections.push(
      JSON.stringify(
        {
          promptTokens: u.promptTokens,
          completionTokens: u.completionTokens,
          totalTokens: total,
          cachedTokens: u.cachedTokens,
          reasoningTokens: u.reasoningTokens,
        },
        null,
        2,
      ),
    );
    sections.push('```');
    sections.push('');
    sections.push('</details>');
  }

  /**
   * Appends the Messages section with each message formatted.
   *
   * @param messages - The chat messages.
   * @param reasoningSources - Indices of assistant messages
   *   whose reasoning was backfilled from the cache.
   * @param sections - The output sections array to append to.
   */
  private static buildMessagesBlock(
    messages: OpenAIMessage[],
    reasoningSources: ReadonlySet<number> | null,
    sections: string[],
  ): void {
    sections.push('## Messages');
    sections.push('');

    for (let i = 0; i < messages.length; i++) {
      ChatDebugLogger.buildSingleMessage(messages[i], i, reasoningSources, sections);
    }
  }

  /**
   * Appends a single chat message as a Markdown sub-section.
   *
   * @param msg - The message to format.
   * @param index - Zero-based message index.
   * @param reasoningSources - Indices of assistant messages
   *   whose reasoning was backfilled from the cache.
   * @param sections - The output sections array to append to.
   */
  private static buildSingleMessage(
    msg: OpenAIMessage,
    index: number,
    reasoningSources: ReadonlySet<number> | null,
    sections: string[],
  ): void {
    const label = formatRoleLabel(msg);
    sections.push(`### Message ${index + 1} (${label})`);
    sections.push('');

    // Reasoning block (first, if present)
    const msgReasoning = extractReasoning(msg);
    if (msgReasoning) {
      const source =
        msg.role === 'assistant' && reasoningSources?.has(index) ? 'cache' : 'thinking-part';
      sections.push('~~~md');
      sections.push(`🧠 Reasoning · source: ${source}`);
      sections.push(msgReasoning);
      const fieldsSummary = formatReasoningFieldsSummary(msg);
      if (fieldsSummary) {
        sections.push('');
        sections.push(fieldsSummary);
      }
      sections.push('~~~');
      sections.push('');
    }

    // Content + tool calls block
    sections.push('~~~md');
    const textContent = extractTextContent(msg.content);
    if (textContent) {
      sections.push(textContent);
    }

    // Image parts
    const imageParts = extractImageParts(msg.content);
    for (const img of imageParts) {
      if (img.mimeType !== 'unknown') {
        const sizeKb = (img.sizeBytes / 1024).toFixed(1);
        sections.push(`🖼️ Image (${img.mimeType}, ${sizeKb} KB)`);
      } else {
        sections.push(`🖼️ Image (external URL)`);
      }
    }

    if (msg.tool_calls) {
      for (const tc of msg.tool_calls) {
        sections.push('');
        sections.push(`🛠️ ${tc.function.name} ${tc.function.arguments}`);
      }
    }
    sections.push('~~~');
    sections.push('');
  }

  /**
   * Appends the Response section with error, cancellation,
   * or success content.
   *
   * @param input - The request-response data.
   * @param sections - The output sections array to append to.
   */
  private static buildResponseBlock(input: LogRequestInput, sections: string[]): void {
    sections.push('## Response');
    sections.push('');

    if (input.error) {
      sections.push('### Error');
      sections.push('');
      sections.push('~~~');
      sections.push(input.error);
      sections.push('~~~');
    } else if (input.cancelled && !input.responseContent) {
      sections.push('*Request was cancelled. No response received.*');
    } else {
      if (input.cancelled) {
        sections.push('*Request was cancelled. Partial response:*');
        sections.push('');
      }

      // Render response reasoning when present
      if (input.responseReasoning) {
        sections.push('### Reasoning');
        sections.push('');
        sections.push('~~~');
        sections.push(input.responseReasoning);
        const fieldsSummary = formatReasoningFieldsSummary(input.responseReasoningFields ?? {});
        if (fieldsSummary) {
          sections.push('');
          sections.push(fieldsSummary);
        }
        sections.push('~~~');
        sections.push('');
      }

      sections.push('### Assistant');
      sections.push('');
      sections.push('~~~md');
      if (input.responseContent) {
        sections.push(input.responseContent);
      }
      if (input.responseToolCalls.length > 0) {
        for (const tc of input.responseToolCalls) {
          sections.push('');
          sections.push(`🛠️ ${tc.name} ${tc.arguments}`);
        }
      }
      sections.push('~~~');
    }
    sections.push('');
  }

  /**
   * Logs a chat request-response pair as a Markdown file.
   *
   * Checks if debug logging is enabled before writing.
   * Uses the pre-resolved session ID for the directory
   * structure, writes atomically (temp + rename), then
   * refreshes the tree view. Errors are silently swallowed.
   *
   * @param input - The request-response data to log.
   */
  logRequest(input: LogRequestInput): void {
    try {
      const settings = this.settingsService.getSettings();
      if (!settings.enabled) {
        this.logger.trace('Debug log skipped: debug logging disabled');
        return;
      }

      const workspaceId = ChatDebugLogger.computeWorkspaceId(input.workspaceFolderUri);

      const { sessionId } = input;
      const requestId = input.requestId;
      const timestamp = ChatDebugLogger.formatTimestamp(input.startTime);
      const fileName = `${timestamp}-${requestId}.md`;

      const sanitizedModel = ChatDebugLogger.sanitizeModelName(input.modelName);
      const sessionDirName = `${sanitizedModel}--${sessionId}`;

      const sessionDir = join(this.logsBasePath, workspaceId, sessionDirName);
      mkdirSync(sessionDir, { recursive: true });

      const filePath = join(sessionDir, fileName);
      const tmpPath = `${filePath}.tmp`;

      const content = ChatDebugLogger.formatLogMarkdown(input, requestId);

      // Atomic write: temp file + rename
      writeFileSync(tmpPath, content, 'utf-8');
      renameSync(tmpPath, filePath);

      this.logger.debug(
        'Debug log written',
        `file=${fileName}`,
        `session=${sessionId.slice(0, 8)}...`,
        `model=${input.modelName}`,
      );

      // Fire refresh callback after successful write.
      this.onLogWrite?.();
    } catch (error: unknown) {
      this.logger.warn(
        'Failed to write debug log',
        error instanceof Error ? error.message : String(error),
      );
    }
  }
}
