import type {
  ProviderInfo,
  ModelInfo,
  FetchedModel,
  ModelDefaultsResult,
  UsageRecordInfo,
  UsageStatsSummary,
} from '@tokenguard/shared';

/** Sample provider entries for the mock API. */
export const sampleProviders: ProviderInfo[] = [
  {
    id: 'prov-openai',
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
  },
  {
    id: 'prov-anthropic',
    name: 'Anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
  },
  {
    id: 'prov-alibaba',
    name: 'Alibaba',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
  },
];

/** Sample configured models for the mock API. */
export const sampleModels: ModelInfo[] = [
  {
    id: 'gpt-4o',
    providerId: 'prov-openai',
    displayName: 'GPT-4o',
    maxContextWindowTokens: 128_000,
    maxOutputTokens: 16_384,
    streaming: true,
    vision: true,
    temperature: null,
    topP: null,
    frequencyPenalty: null,
    presencePenalty: null,
    defaultReasoningEffort: null,
    reasoningEffortMap: null,
    preserveReasoning: false,
    inputCostPer1m: 2.5,
    outputCostPer1m: 10.0,
    cachedInputCostPer1m: 1.25,
    cacheControl: null,
    customFields: null,
  },
  {
    id: 'claude-sonnet-4-20250514',
    providerId: 'prov-anthropic',
    displayName: 'Claude Sonnet 4',
    maxContextWindowTokens: 200_000,
    maxOutputTokens: 16_000,
    streaming: true,
    vision: true,
    temperature: null,
    topP: null,
    frequencyPenalty: null,
    presencePenalty: null,
    defaultReasoningEffort: 'medium',
    reasoningEffortMap:
      '{"low":{"reasoning":{"effort":"low"}},"medium":{"reasoning":{"effort":"medium"}},"high":{"reasoning":{"effort":"high"}}}',
    preserveReasoning: true,
    inputCostPer1m: 3.0,
    outputCostPer1m: 15.0,
    cachedInputCostPer1m: 0.3,
    cacheControl: null,
    customFields: null,
  },
  {
    id: 'qwen3-235b-a22b',
    providerId: 'prov-alibaba',
    displayName: 'Qwen3 235B A22B',
    maxContextWindowTokens: 131_072,
    maxOutputTokens: 16_384,
    streaming: true,
    vision: false,
    temperature: null,
    topP: null,
    frequencyPenalty: null,
    presencePenalty: null,
    defaultReasoningEffort: null,
    reasoningEffortMap: null,
    preserveReasoning: false,
    inputCostPer1m: 0.3,
    outputCostPer1m: 1.2,
    cachedInputCostPer1m: 0.03,
    cacheControl: {
      enabled: true,
      maxMarkers: 4,
    },
    customFields: null,
  },
];

/** Models returned by a simulated /v1/models fetch. */
export const sampleFetchedModels: FetchedModel[] = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    maxContextWindowTokens: 128_000,
    maxOutputTokens: 16_384,
    defaultReasoningEffort: null,
    vision: true,
    supportedReasoningEfforts: null,
    inputCostPer1M: null,
    outputCostPer1M: null,
    cachedInputCostPer1M: null,
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    maxContextWindowTokens: 128_000,
    maxOutputTokens: 16_384,
    defaultReasoningEffort: null,
    vision: true,
    supportedReasoningEfforts: null,
    inputCostPer1M: null,
    outputCostPer1M: null,
    cachedInputCostPer1M: null,
  },
  {
    id: 'o3-mini',
    name: 'o3-mini',
    maxContextWindowTokens: 200_000,
    maxOutputTokens: 100_000,
    defaultReasoningEffort: 'medium',
    vision: false,
    supportedReasoningEfforts: ['none', 'low', 'medium', 'high'],
    inputCostPer1M: null,
    outputCostPer1M: null,
    cachedInputCostPer1M: null,
  },
];

/** Bundled model defaults for the mock API. */
export const sampleDefaults: ModelDefaultsResult = {
  contextSize: 128_000,
  maxTokens: 16_384,
  inputCostPer1M: 2.5,
  outputCostPer1M: 10.0,
  cachedInputCostPer1M: 1.25,
  supportedCapabilities: ['streaming', 'vision'],
};

/** Sample usage records for the playground. */
export const sampleUsageRecords: UsageRecordInfo[] = [
  {
    providerId: 'prov-openai',
    modelId: 'gpt-4o',
    date: '2026-05-20',
    promptTokens: 12_500,
    completionTokens: 3_200,
    cachedTokens: 4_000,
    reasoningTokens: 0,
    requestCount: 15,
    errorCount: 0,
    promptTokensCost: 0.02125,
    completionTokensCost: 0.032,
    cachedTokensCost: 0.005,
  },
  {
    providerId: 'prov-openai',
    modelId: 'gpt-4o',
    date: '2026-05-21',
    promptTokens: 18_000,
    completionTokens: 5_100,
    cachedTokens: 6_000,
    reasoningTokens: 0,
    requestCount: 22,
    errorCount: 1,
    promptTokensCost: 0.03,
    completionTokensCost: 0.051,
    cachedTokensCost: 0.0075,
  },
  {
    providerId: 'prov-openai',
    modelId: 'gpt-4o',
    date: '2026-05-22',
    promptTokens: 9_800,
    completionTokens: 2_400,
    cachedTokens: 2_000,
    reasoningTokens: 0,
    requestCount: 10,
    errorCount: 0,
    promptTokensCost: 0.0195,
    completionTokensCost: 0.024,
    cachedTokensCost: 0.0025,
  },
  {
    providerId: 'prov-anthropic',
    modelId: 'claude-sonnet-4-20250514',
    date: '2026-05-20',
    promptTokens: 20_000,
    completionTokens: 6_000,
    cachedTokens: 8_000,
    reasoningTokens: 1_500,
    requestCount: 8,
    errorCount: 0,
    promptTokensCost: 0.036,
    completionTokensCost: 0.09,
    cachedTokensCost: 0.0024,
  },
  {
    providerId: 'prov-anthropic',
    modelId: 'claude-sonnet-4-20250514',
    date: '2026-05-21',
    promptTokens: 15_000,
    completionTokens: 4_500,
    cachedTokens: 3_000,
    reasoningTokens: 1_200,
    requestCount: 6,
    errorCount: 0,
    promptTokensCost: 0.036,
    completionTokensCost: 0.0675,
    cachedTokensCost: 0.0009,
  },
  {
    providerId: 'prov-anthropic',
    modelId: 'claude-sonnet-4-20250514',
    date: '2026-05-22',
    promptTokens: 22_000,
    completionTokens: 7_800,
    cachedTokens: 10_000,
    reasoningTokens: 2_000,
    requestCount: 12,
    errorCount: 0,
    promptTokensCost: 0.036,
    completionTokensCost: 0.117,
    cachedTokensCost: 0.003,
  },
  {
    providerId: 'prov-openai',
    modelId: 'gpt-4o',
    date: '2026-05-23',
    promptTokens: 14_000,
    completionTokens: 3_800,
    cachedTokens: 5_000,
    reasoningTokens: 0,
    requestCount: 18,
    errorCount: 0,
    promptTokensCost: 0.0225,
    completionTokensCost: 0.038,
    cachedTokensCost: 0.00625,
  },
  {
    providerId: 'prov-anthropic',
    modelId: 'claude-sonnet-4-20250514',
    date: '2026-05-23',
    promptTokens: 25_000,
    completionTokens: 9_000,
    cachedTokens: 7_000,
    reasoningTokens: 3_000,
    requestCount: 10,
    errorCount: 1,
    promptTokensCost: 0.054,
    completionTokensCost: 0.135,
    cachedTokensCost: 0.0021,
  },
];

/** Sample usage stats summary for the playground. */
export const sampleUsageSummary: UsageStatsSummary = {
  totalPromptTokens: 136_300,
  totalCompletionTokens: 41_800,
  totalCachedTokens: 45_000,
  totalReasoningTokens: 7_700,
  totalRequestCount: 101,
  totalErrorCount: 2,
  totalEstimatedCost: 0.75385,
  providerNames: {
    'prov-openai': { name: 'OpenAI', removed: false },
    'prov-anthropic': { name: 'Anthropic', removed: false },
    'prov-removed': { name: 'Old Provider', removed: true },
  },
  modelNames: {
    'prov-openai:gpt-4o': { name: 'GPT-4o', removed: false },
    'prov-anthropic:claude-sonnet-4-20250514': {
      name: 'Claude Sonnet 4',
      removed: false,
    },
  },
  perModelBreakdown: [
    {
      providerId: 'prov-openai',
      modelId: 'gpt-4o',
      displayName: 'GPT-4o',
      inputCostPer1m: 2.5,
      outputCostPer1m: 10.0,
      cachedInputCostPer1m: 1.25,
      promptTokens: 54_300,
      completionTokens: 14_500,
      cachedTokens: 17_000,
      reasoningTokens: 0,
      promptTokensCost: 0.09325,
      completionTokensCost: 0.145,
      cachedTokensCost: 0.02125,
    },
    {
      providerId: 'prov-anthropic',
      modelId: 'claude-sonnet-4-20250514',
      displayName: 'Claude Sonnet 4',
      inputCostPer1m: 3.0,
      outputCostPer1m: 15.0,
      cachedInputCostPer1m: 0.3,
      promptTokens: 82_000,
      completionTokens: 27_300,
      cachedTokens: 28_000,
      reasoningTokens: 7_700,
      promptTokensCost: 0.162,
      completionTokensCost: 0.4095,
      cachedTokensCost: 0.0084,
    },
  ],
};
